### ISSUE TITLE
검색 결과가 없을 경우의 처리

### ISSUE THREAD

**Issue by adhrinae** [say8425/naver_map_ruby#11]
현재 작성된 코드는 **반드시** 쿼리의 결과가 나온다는 것을 전제로 코드가 작성되어 있으며,
만약 올바른 검색 정보가 입력되지 않았을 경우에는 네이버 서버에서 에러 메세지와 에러 코드를 전송합니다.

[에러 메세지 및 코드 참조](https://developers.naver.com/docs/map/overview)

이 경우에 단순히 'No results' 등의 결과값을 리턴할 것인지 예외처리를 할 것인지 등을 생각해 볼 필요가 있습니다.

예상 시나리오로는 `get_result` 의 결과가 `nil`인 경우
(에러 메세지에는 `:items` 키에 해당하는 값이 없을테니까 `nil` 리턴)
`raise` -> `rescue` 블록에서 에러 메세지를 가져와 출력하는 방법이 있을 수 있겠습니다.

**Comment by say8425** [comment]
```
{
    "errorMessage": "검색 결과가 없습니다.",
    "errorCode": "MP03"
}
```

일단 검색결과가 없다면, 에러 메시지가 반환 되고 있어서
이걸 기반으로 예외 처리해주면 될 거 같아요

아차 그리고 네이버 가이드를 맹신 할 수 없는 게
가이드와 실제 결과물이 다를때가 있어요 ~~이거때문에 처음 작성할때 삽질한 걸 생각하면 ㅂㄷㅂㄷ~~
그래서 가이드를 참고하되 반드시 실제로 쏴봐야해요

**Comment by adhrinae** [comment]
1. 원하는 결과가 없다면 `errorMessage` 조회 후 출력
2. 모종의 이유로 `errorMessage` 조차 없다면 UnknownError 출력

이런식으로 구성해보면 되겠네요

가이드가 제대로 안되어있다니 씁쓸하구만요
