### ISSUE TITLE
지도 API 키 검사

### ISSUE THREAD

**Issue by adhrinae** [say8425/naver_map_ruby#12]
1. 객체를 생성할 때 `initialize` 메서드에서 바로 API 키가 올바른지 네이버에 연결 시도
    - 만약 올바른 키가 아니라면 커스텀 예외 처리
2. 객체 생성 이후 메서드를 호출할 때 어차피 403 에러가 리턴될 테니 그 때 결과 출력

이렇게 두 가지 시나리오를 예상할 수 있겠는데요
보통은 2번 방식으로 처리할텐데, 애초에 제대로 된 API 키 입력이 없으면 `NaverMap` 클래스의 존재의의가 사라지는 것일테니 어느 방법이 효율적일지 고려해볼 필요가 있겠습니다

**Comment by say8425** [comment]
```
{"errorMessage":"NID AUTH Result Invalid (1000) : Authentication failed. (인증에 실패했습니다.)","errorCode":"024"}
```

가이드에서는 키가 틀리면 400번 에러가 반환된다는데 실제로는 024 코드가 반환되더군요
키밸루가 아예 없는 경우에도 역시 024코드가 반환되고 있습니다

클래스를 init 하면서, 동시에 해당키로 네이버 연동을 시도하고 errorCode 여부를 체크하면 충분할 거 같아요

**Comment by adhrinae** [comment]
400번 에러는 HTTP Status Code고 024 코드는 네이버 공통 가이드에서 제공하는 인증 에러 코드인가봅니다 [참조](https://developers.naver.com/docs/common/common_error)

1번 시나리오를 쓰면서 좀 마음에 걸렸던 건데 다시 한번 확인해보니 네이버측에서 연결 테스트로 제공하는 주소는 따로 없네요

그렇게 되면 `initialize` 호출 시 임의의 주소나 좌표를 불러와야 하는데 이는 매우 비효율적입니다

그래서 그냥 실제 메서드 호출 시 에러가 발생하면 처리하는 방향으로 가야겠습니다
이 부분은 직전에 발행한 이슈랑 겹치므로 이 이슈는 닫아도 되겠네요

**Comment by say8425** [comment]
인그래도 어제 1번을 기반으로 작업해봤는데 아무리 생각해도 비효율적이더라요 그래서 저도 중간에 접었습니다 이건 접죠

**Comment by say8425** [comment]
생각이 바꼈어요 소스 측면에서는 상당히 비효율적인 행동이기는 한데
사용자 입장에서는 상당히 어색한,, 별로 좋지 못한 UX인거 같아요.

애초에 init을 할때 키의 유효성을 알려줘야지
함수 호출할때서야 키가 유효하지 않다고 알려주는 것은
썩 좋은 사용자 경험이 아닌 거 같아요.

비효율적인 건 알겠는데 이거는 우리를 위해서 개발하지 말고
사용하는 사람들을 위해서 개발하는 것이 맞는 거 같아요.

**Comment by adhrinae** [comment]
맞는 말씀입니다
방법은 조금 더 고민해보도록 하지요

**Comment by say8425** [comment]
어제 다른 루비 개발자 분과 이거에 대해서 얘기했는데
핵심을 찌르는 말을 하시더라요

> 메모리 할당하는 함수에 왜 서버 통신하는 코드가 들어가야하죠?

그 한마디에 정말 윽! 했어서 init은 그냥 냅두고 타입 체크하는 선에서 마무리 지어야 할 거 같습니다

**Comment by adhrinae** [comment]
제가 해싱에 대해서 잘 몰라서 그런데
네이버가 넘겨주는 API에 일정 규칙이 있다면 그 틀에 맞는지만 검사해도 되지 않을까요
그게 아니라면 최소 `String` 인지만 검사해야겠지요

**Comment by adhrinae** [comment]
저도 임의로 API를 발급받아보았는데 길이 규칙은 있나보네요
- `client_id`: 20자 이상의 `String`
- `client_secret`: 10자 이상의 `String`

인자를 받자마자 위 조건을 검사하고
맞지 않으면 `InvalidKeysError` 라는 임의의 에러를 발생하도록 만들어봐야겠습니다
