### ISSUE TITLE
싱글 value일 경우 array로 받아오지 않게함

### ISSUE THREAD

**Issue by say8425** [say8425/naver_map_ruby#8]
AR의 `Model.last`에서 영감을 받음

**Comment by adhrinae** [comment]
참고로 Ruby Array 클래스의 `first`, `last` 메서드도 같은 방식으로 동작합니다.
`first` 메서드는 `Enumerable` 모듈에서 제공하지만
`last` 메서드는 Array, Range 등에서만 사용하실 수 있습니다.
